INSERT INTO products (title, author, description, ownerID, price, image, stock, category)
VALUES
    ('Book 1', 'Author A', 'Description of Book 1', 1, 19.99, 'book1.jpg', 100, 'novels'),
    ('Book 2', 'Author B', 'Description of Book 2', 2, 24.99, 'book2.jpg', 50, 'novels'),
    ('Book 3', 'Author C', 'Description of Book 3', 1, 14.99, 'book3.jpg', 75, 'novels'),
    ('Health Product', 'Health Company', 'Description of Health Product', 4, 49.99, 'health_product.jpg', 200, 'health'),
    ('IT Course', 'IT Academy', 'Description of IT Course', 5, 199.99, 'it_course.jpg', 30, 'IT'),
    ('Environmental Book', 'Author D', 'Description of Environmental Book', 6, 29.99, 'environment_book.jpg', 80, 'environment'),
    ('Book 4', 'Author A', 'Description of Book 4', 1, 29.99, 'book4.jpg', 60, 'novels'),
    ('Book 5', 'Author B', 'Description of Book 5', 2, 34.99, 'book5.jpg', 40, 'novels'),
    ('Book 6', 'Author C', 'Description of Book 6', 1, 17.99, 'book6.jpg', 90, 'novels'),
    ('Health Supplement', 'Health Company', 'Description of Health Supplement', 4, 59.99, 'health_supplement.jpg', 150, 'health'),
    ('Web Development Course', 'IT Academy', 'Description of Web Development Course', 5, 249.99, 'web_dev_course.jpg', 25, 'IT'),
    ('Environmental Documentary', 'Author D', 'Description of Environmental Documentary', 6, 39.99, 'environment_doc.jpg', 70, 'environment'),
    ('Book 7', 'Author A', 'Description of Book 7', 1, 21.99, 'book7.jpg', 80, 'novels'),
    ('Book 8', 'Author B', 'Description of Book 8', 2, 27.99, 'book8.jpg', 45, 'novels'),
    ('Book 9', 'Author C', 'Description of Book 9',2, 12.99, 'book9.jpg', 85, 'novels'),
    ('Vitamin C', 'Health Company', 'Description of Vitamin C', 4, 29.99, 'vitamin_c.jpg', 180, 'health'),
    ('Python Course', 'IT Academy', 'Description of Python Course', 5, 149.99, 'python_course.jpg', 35, 'IT'),
    ('Climate Change Book', 'Author D', 'Description of Climate Change Book', 6, 24.99, 'climate_change_book.jpg', 90, 'environment'),
    ('Book 10', 'Author A', 'Description of Book 10', 1, 25.99, 'book10.jpg', 70, 'novels'),
    ('Book 11', 'Author B', 'Description of Book 11', 2, 30.99, 'book11.jpg', 60, 'novels'),
    ('Book 12', 'Author C', 'Description of Book 12', 1, 19.99, 'book12.jpg', 100, 'novels'),
    ('Multivitamin', 'Health Company', 'Description of Multivitamin', 2, 39.99, 'multivitamin.jpg', 160, 'health'),
    ('JavaScript Course', 'IT Academy', 'Description of JavaScript Course', 2, 179.99, 'javascript_course.jpg', 40, 'IT'),
    ('Sustainable Living Book', 'Author D', 'Description of Sustainable Living Book', 6, 34.99, 'sustainable_living_book.jpg', 75, 'environment'),
    ('Book 13', 'Author A', 'Description of Book 13', 1, 23.99, 'book13.jpg', 90, 'novels'),
    ('Book 14', 'Author B', 'Description of Book 14', 2, 29.99, 'book14.jpg', 55, 'novels'),
    ('Book 15', 'Author C', 'Description of Book 15', 1, 16.99, 'book15.jpg', 95, 'novels'),
    ('Fish Oil', 'Health Company', 'Description of Fish Oil', 1, 34.99, 'fish_oil.jpg', 140, 'health'),
    ('Java Course', 'IT Academy', 'Description of Java Course', 2, 169.99, 'java_course.jpg', 50, 'IT'),
    ('Wildlife Conservation Book', 'Author D', 'Description of Wildlife Conservation Book', 2, 31.99, 'wildlife_conservation_book.jpg', 65, 'environment');


